### ISSUE TITLE
Copy the event photo into repo

### ISSUE THREAD

**Issue by leehack** [AndroidMontreal/DevFest2024#3]
It seems the Google photo links aren't stable. Why don't we just copy them into the repo?

**Comment by amanmishra7ave** [comment]
it would be good to use google drive

**Comment by leehack** [comment]
> it would be good to use google drive

Just curious. What's the problem with putting the photos into repo? due to the size?
If it's not too big, I prefer centralize everything in the repo since it's a static web. I wish not to add any outside dependency if we can avoid it.

**Comment by Solankimimoh** [comment]
We can copy events photos in images/eventPhotos to keep everything at one place. Initially was thinking to avoid create folder for event photos as we have Google Photos link but it can be issue load sometimes ( Too many requests ).
