### ISSUE TITLE
Partner(Organizer) logos are too small

### ISSUE THREAD

**Issue by leehack** [AndroidMontreal/DevFest2024#8]
<img width="1293" alt="image" src="https://github.com/user-attachments/assets/60a18779-55c6-4bb2-88e4-529623699bd0">

**Comment by Solankimimoh** [comment]
Yes, Need to correct according guideline.

**Comment by leehack** [comment]
Yeah. I think the white space is too big. Also the margin outside of the whitespace could be reduced.
