### ISSUE TITLE
Maybe too many previous year photos

### ISSUE THREAD

**Issue by leehack** [AndroidMontreal/DevFest2024#9]
I find it's too many photos, especially on the mobile view.
Maybe we could put 9 maximum for Desktop view and 3-5 for mobile view.

Probably it would be even better if we make it a carousel.

**Comment by Solankimimoh** [comment]
Total images reduced to 7 for now.  Event photos carousel idea is good but users might miss photos if they don't actively interact with the carousel or need to wait for auto carousel to load last photo.

If we still consider carousel then

-- https://swiperjs.com/demos
-- https://www.embla-carousel.com/examples/predefined/

**Comment by leehack** [comment]
With 7 photos on mobile, it doesn't look too bad but I still prefer the sliding carousel. I think the photo makes the user scroll down uselessly.
